export const advisor = {
  name: 'Seokhwan Jeong, Ph.D.',
  photo: '/images/team/seokhwan-jeong-portrait.jpg',
  title: 'Associate Professor, Department of Mechanical Engineering, Sogang University',
  office: 'Room 236, Building K, Sogang University, Seoul, Korea',
  phone: '+82-2-705-7886',
  cv: 'https://drive.google.com/file/d/1Od3EuGPwVmM5kRFyMun_c2io94LxQXQ6/view',
  email: 'seokhwan@sogang.ac.kr',
  interests: [
    'Novel actuator design & mechanisms — variable transmissions, magnetic gears, twisted string actuation',
    'Robot hands, grippers, and prosthetics with AI-based grasping',
    'Medical robotics — steerable neuro-endoscope robots and guidewires',
    'Hand exoskeletons for rehabilitation',
    'Robust control theory and miniature force sensor design',
  ],
  education: [
    { period: '2015 – 2018', text: 'Ph.D. in Mechanical Engineering, KAIST — Design and Control of Twisted String-based Compact Actuation Mechanism for Robotic Systems (Advisor: Prof. Kyung-Soo Kim)' },
    { period: '2013 – 2015', text: 'M.S. in Mechanical Engineering, KAIST — Design and Control of a Twisted Actuator with an Active Mode Change for a Robot Hand' },
    { period: '2007 – 2013', text: 'B.S. in Mechanical Engineering, Yonsei University' },
  ],
  career: [
    { period: '2025 – present', text: 'Associate Professor, Sogang University' },
    { period: '2021 – 2025', text: 'Assistant Professor, Sogang University' },
    { period: '2018 – 2020', text: 'Postdoctoral Researcher, Biomedical Engineering, Georgia Institute of Technology (Advisor: Prof. Jaydev P. Desai)' },
  ],
  editorial: [
    { period: '2024 – present', text: 'Technical Editor, IEEE/ASME Transactions on Mechatronics' },
    { period: '2024 – present', text: 'Associate Editor, IEEE Robotics and Automation Letters' },
    { period: '2026', text: 'Associate Editor, IEEE/ASME AIM 2026 · Associate Editor, IEEE/RSJ IROS 2026' },
    { period: '2024', text: 'Associate Editor, IEEE BioRob 2024 · Associate Editor, UR 2024' },
    { period: '2023 – present', text: 'Organizing Committee — ICCAS 2025·2026, ICNR 2026, ICROS 2024·2025, KRoC 2023·2024' },
    { period: '2022 – present', text: 'Executive Board Member — KSME Dynamics, Control & Robotics Div. (2023–) · Military Robotics Society (2022–) · KSMTE Robotics & Automation Div. (2024–)' },
  ],
  honors: [
    { period: '2026 – 2027', text: 'Fulbright Scholar Program (for Faculty and Professionals)' },
    { period: '2026', text: 'RED Show Excellence Award, Korea Robotics Society Annual Conference' },
    { period: '2025', text: 'Young Scientist Award, Korea Robotics Society (KROS)' },
    { period: '2025', text: 'Best Paper Award, ICROS' },
    { period: '2024', text: 'Outstanding Young Researcher Award & Best Paper Award, ICROS · RED Show Grand Prize & Outstanding Paper Award (Undergrad), KRoC' },
    { period: '2023', text: 'Outstanding Paper Award, ICROS' },
    { period: '2022', text: 'Outstanding Paper Award, KSME IT Convergence Division' },
    { period: '2021', text: 'Best Paper Award, Korean Society for Precision Engineering (KSPE)' },
    { period: '2018', text: 'Best Paper Award, ICROS' },
    { period: '2016 – 2017', text: 'Best Student Paper Award, IEEE/ASME AIM 2016 · Best Mechatronics Student Paper Award, ASME/DSCD Mechatronics TC' },
  ],
};
