export type NewsCategory = 'Announcement' | 'Conference' | 'Award' | 'Grant' | 'Publication' | 'Members' | 'Lab Life';

export type NewsItem = {
  date: string; // YYYY.MM or YYYY.MM.DD
  title: string;
  category: NewsCategory;
  body?: string;
  link?: string;
  /** Optional photo shown with the item (path under /public) */
  image?: string;
  /** Additional photos (paths under /public) shown as a gallery after `image` */
  images?: string[];
  /** Additional labeled links */
  links?: { href: string; label: string }[];
};

export const news: NewsItem[] = [
  { date: '2026.11', title: 'KSME Annual Meeting 2026, Jeju (upcoming)', category: 'Conference', body: 'Prof. Jeong will give an oral presentation on robot hand and gripper design and control optimized for physical-AI learning environments at the KSME Annual Meeting (Nov 11–14, ICC Jeju), with lab members presenting their work.' },
  { date: '2026.08', title: 'New RIM Lab website launched', category: 'Announcement', body: 'The lab homepage was fully rebuilt with updated research projects, publications, patents, and news.', link: 'https://rim-lab.vercel.app' },
  { date: '2026.08', title: 'Prof. Jeong selected as a Fulbright Visiting Scholar', category: 'Award', body: 'Prof. Seokhwan Jeong was selected for the Fulbright Visiting Scholar Program (PY 2027) for research in the United States.' },
  { date: '2026.08', title: 'Graduation — Chunghyeon Lee (M.S.)', category: 'Members', body: 'Chunghyeon Lee received his M.S. degree and will join Texas A&M University as a Ph.D. student. Congratulations!', image: '/images/news/2026-08-graduation.jpg', images: ['/images/news/2026-08-graduation-2.jpg'] },
  { date: '2026.07', title: 'ICROS 2026, Daegu EXCO', category: 'Conference', body: 'RIM Lab members participated in ICROS 2026 at Daegu EXCO, where the lab also presented its lab-introduction poster; Prof. Jeong served on the organizing committee.', image: '/images/news/2026-07-icros.jpg', images: ['/images/news/2026-07-icros-2.jpg', '/images/news/2026-07-icros-3.jpg'] },
  { date: '2026.07', title: 'AIM 2026, Genova, Italy', category: 'Conference', body: 'The lab attended IEEE/ASME AIM 2026 in Genova, Italy.', image: '/images/news/2026-07-aim.jpg', images: ['/images/news/2026-07-aim-2.jpg', '/images/news/2026-07-aim-3.jpg'] },
  { date: '2026.07', title: 'Workspace 3 moved to TE608A', category: 'Lab Life', body: 'The lab\'s third workspace moved from TE208 to the larger room 608A on the 6th floor of Teilhard Hall (July 1, 2026).' },
  { date: '2026.07', title: 'NANO KOREA 2026 — electroadhesive gripper demo', category: 'Conference', image: '/images/news/2026-07-nano-korea.jpg', images: ['/images/news/2026-07-nano-korea-2.jpg', '/images/news/2026-07-nano-korea-3.jpg'], body: "At the Nano Convergence R&D showcase of NANO KOREA 2026 (July 8-10, KINTEX), the lab demonstrated its 9-DOF direct-drive-differential gripper carrying the high-dielectric electroadhesion pads developed with Prof. Hyung-Jun Kim's group — grasping controlled by voltage alone." },
  { date: '2026.07', title: 'KEITI environmental robotics project underway', category: 'Grant', body: 'Kickoff of the KEITI field-demand program on an unmanned, enclosed robotic–AI platform for fully automated hazardous-chemical analysis, jointly with the Sogang Bio-Interface Institute and Tesollo.' },
  { date: '2026.06', title: 'MOTIE R&D project selected (Digital Healthcare)', category: 'Grant', body: 'Our proposal for the bio-industry technology development program (digital healthcare) was accepted.', image: '/images/news/2026-06-motie.jpg' },
  { date: '2026.06', title: 'Undergraduate internship news', category: 'Members', body: 'Updates from our undergraduate research internship program.', image: '/images/news/2026-06-intern.jpg', images: ['/images/news/2026-06-intern-2.jpg'], links: [{ href: 'https://www.instagram.com/p/DZpDl47Ewbh/', label: 'Instagram' }, { href: 'https://blog.naver.com/sogangpr/224313660600', label: 'Sogang PR blog' }] },
  { date: '2026.05', title: 'ICRA 2026, Vienna, Austria', category: 'Conference', body: 'RIM Lab presented and participated at IEEE ICRA 2026 in Vienna.', image: '/images/news/2026-05-icra.jpg', images: ['/images/news/2026-05-icra-2.jpg', '/images/news/2026-05-icra-3.jpg', '/images/news/2026-05-icra-4.jpg', '/images/news/2026-05-icra-5.jpg', '/images/news/2026-05-icra-6.jpg'] },
  { date: '2026.04', title: 'RIM Lab featured in Robot News', category: 'Announcement', body: "Prof. Jeong was featured in Robot News' 'Young Robot Engineers' series (no. 91).", image: '/images/news/2026-04-robot-news-2.jpg', images: ['/images/news/2026-04-robot-news-3.jpg', '/images/news/2026-04-robot-news.jpg'], link: 'https://www.irobotnews.com/news/articleView.html?idxno=45592' },
  { date: '2026.02', title: 'KROC 2026 RED Show — Excellence Award', category: 'Award', body: 'Edgar Lee, Junho Choi, and Chihyun Han received the Excellence Award (general category) at the KROC 2026 RED Show.', image: '/images/news/2026-02-kroc-red-show-award.jpg', images: ['/images/news/2026-02-kroc-red-show-award-2.jpg', '/images/news/2026-02-kroc-red-show-award-3.jpg'] },
  { date: '2026.02', title: 'KROC 2026 participation', category: 'Conference', body: 'The lab participated in the Korea Robotics Society Annual Conference 2026.', image: '/images/news/2026-02-kroc.jpg', images: ['/images/news/2026-02-kroc-2.jpg', '/images/news/2026-02-kroc-3.jpg', '/images/news/2026-02-kroc-4.jpg', '/images/news/2026-02-kroc-5.jpg'] },
  { date: '2025.12', title: 'Young Scientist Award, KROS', category: 'Award', body: 'Prof. Seokhwan Jeong received the Young Scientist Award from the Korea Robotics Society, recognizing excellence in robotic actuation research.', image: '/images/news/2025-12-kros-award.jpg', images: ['/images/news/2025-12-kros-award-2.jpg', '/images/news/2025-12-kros-award-3.jpg'] },
  { date: '2025.12', title: 'KSME Annual Meeting 2025', category: 'Conference', body: 'RIM Lab participated in the KSME Annual Meeting 2025.' },
  { date: '2025.10', title: 'Lab renovation', category: 'Lab Life', body: 'Our research space was renovated for a better research environment.', image: '/images/news/2025-10-lab-renovation.jpg', images: ['/images/news/2025-10-lab-renovation-2.jpg', '/images/news/2025-10-lab-renovation-3.jpg', '/images/news/2025-10-lab-renovation-4.jpg', '/images/news/2025-10-lab-renovation-5.jpg'] },
  { date: '2025.09', title: 'NRF national agenda project selected', category: 'Grant', body: 'Funding awarded for robotic hand/gripper platform hardware and control technologies.', image: '/images/news/2025-09-nrf-agenda.jpg' },
  { date: '2025.08', title: 'NRF Materials Global Young Connect selected', category: 'Grant', body: 'New project on high-dielectric elastomers for electroadhesive robotic end-effectors.' },
  { date: '2025.06', title: 'IEEE RAM review paper published', category: 'Publication', body: '"Variable Transmission Mechanisms for Robotic Applications: A Review" was officially published in IEEE Robotics and Automation Magazine.', image: '/images/news/2025-06-ram-review.jpg' },
  { date: '2025.06', title: 'ICROS 2025 Excellence Paper Award', category: 'Award', body: 'Third consecutive year receiving a top paper award at ICROS.', image: '/images/news/2025-06-icros-award.jpg', images: ['/images/news/2025-06-icros-award-2.jpg', '/images/news/2025-06-icros-award-3.jpg', '/images/news/2025-06-icros-award-4.jpg'] },
  { date: '2025.05', title: 'ICRA 2025, Atlanta, USA', category: 'Conference', body: 'RIM Lab participated in IEEE ICRA 2025.', image: '/images/news/2025-05-icra.jpg', images: ['/images/news/2025-05-icra-2.jpg', '/images/news/2025-05-icra-3.jpg', '/images/news/2025-05-icra-4.jpg', '/images/news/2025-05-icra-5.jpg', '/images/news/2025-05-icra-6.jpg'] },
  { date: '2025.05', title: "Teacher's Day lab meeting", category: 'Lab Life', body: "A lab gathering to celebrate Teacher's Day.", image: '/images/news/2025-05-teachers-day.jpg', images: ['/images/news/2025-05-teachers-day-2.jpg'] },
  { date: '2025.02', title: 'KROC 2025 — RED Show & workshop', category: 'Conference', body: 'RED show exhibition and workshop presentations at KROC 2025.', image: '/images/news/2025-02-kroc-red-show.jpg', images: ['/images/news/2025-02-kroc-red-show-2.jpg'] },
  { date: '2024.07', title: 'ICROS 2024 — Excellence Paper Awards & Young Researcher Award', category: 'Award', body: 'Jungwoo Hur and Hangyeol Song received excellence paper awards; Prof. Jeong received the Young Researcher Award.', image: '/images/news/2024-07-icros-awards.jpg', images: ['/images/news/2024-07-icros-awards-2.jpg', '/images/news/2024-07-icros-awards-3.jpg', '/images/news/2024-07-icros-awards-4.jpg', '/images/news/2024-07-icros-awards-5.jpg', '/images/news/2024-07-icros-awards-6.jpg'] },
  { date: '2024.05', title: 'Advanced Intelligent Systems journal cover', category: 'Publication', body: 'Our modular robotic platform for biological research was featured on the journal cover.', image: '/images/news/2024-05-ais-cover.jpg', link: 'https://onlinelibrary.wiley.com/doi/10.1002/aisy.202300566' },
  { date: '2024.05', title: 'ICRA 2024, Yokohama, Japan', category: 'Conference', body: 'The lab participated in IEEE ICRA 2024.', image: '/images/news/2024-05-icra.jpg', images: ['/images/news/2024-05-icra-2.jpg', '/images/news/2024-05-icra-3.jpg'] },
  { date: '2024.02', title: 'KROC 2024 — paper awards & RED Show top honors', category: 'Award', body: 'Excellence paper awards and top honors at the KROC 2024 RED Show.', image: '/images/news/2024-02-kroc-red-show.jpg', images: ['/images/news/2024-02-kroc-red-show-2.jpg', '/images/news/2024-02-kroc-red-show-3.jpg', '/images/news/2024-02-kroc-red-show-4.jpg', '/images/news/2024-02-kroc-red-show-5.jpg', '/images/news/2024-02-kroc-red-show-6.jpg'] },
  { date: '2024.02', title: 'Graduation — Sungho Chung, Seungmin Lee, Jaehyun Lee', category: 'Members', body: 'Three M.S. students graduated. Congratulations!', image: '/images/news/2024-02-graduation.jpg' },
  { date: '2023.12', title: 'Hangyeol Song selected as Fulbright Scholar', category: 'Members', body: 'M.S. graduate Hangyeol Song was selected for the Fulbright scholarship for Ph.D. study in the USA.', image: '/images/news/2023-12-fulbright.jpg', link: 'https://www.sogang.ac.kr/front/boardview.do?pkid=540711&currentPage=1&searchField=ALL&siteGubun=1&menuGubun=1&bbsConfigFK=58&searchLowItem=ALL&searchValue=' },
  { date: '2023.11', title: 'Experimental setups', category: 'Lab Life', body: 'Robot experiment setups built up in the lab.', image: '/images/news/2023-11-experimental-setups.jpg' },
  { date: '2023.10', title: 'IROS 2023, Detroit, USA', category: 'Conference', body: 'The lab attended IEEE/RSJ IROS 2023.', image: '/images/news/2023-10-iros.jpg', images: ['/images/news/2023-10-iros-2.jpg', '/images/news/2023-10-iros-3.jpg', '/images/news/2023-10-iros-4.jpg'] },
  { date: '2023.09', title: 'Lab meeting with pizza', category: 'Lab Life', body: 'A casual lab gathering.', image: '/images/news/2023-09-pizza.jpg', images: ['/images/news/2023-09-pizza-2.jpg', '/images/news/2023-09-pizza-3.jpg', '/images/news/2023-09-pizza-4.jpg'] },
  { date: '2023.08', title: 'Graduation — Seung Kyo Jeong, Hangyeol Song', category: 'Members', body: 'Two M.S. students graduated.', image: '/images/news/2023-08-graduation.jpg', images: ['/images/news/2023-08-graduation-2.jpg', '/images/news/2023-08-graduation-3.jpg'] },
  { date: '2023.06', title: 'NRF Basic Research Lab (기초연구실) selected', category: 'Grant', body: 'Selected for the NRF Basic Research Laboratory program.', image: '/images/news/2023-06-nrf-brl.jpg' },
  { date: '2023.06', title: 'ICROS 2023, Samcheok', category: 'Conference', body: 'The lab participated in ICROS 2023.', image: '/images/news/2023-06-icros.jpg', images: ['/images/news/2023-06-icros-2.jpg', '/images/news/2023-06-icros-3.jpg', '/images/news/2023-06-icros-4.jpg', '/images/news/2023-06-icros-5.jpg', '/images/news/2023-06-icros-6.jpg'] },
  { date: '2023.05', title: 'MERRIC webinar', category: 'Announcement', body: 'Invited webinar on high-performance anthropomorphic prosthetic hand systems by Prof. Jeong and Dr. Younggeol Cho.', link: 'https://www.youtube.com/watch?v=gCsYF04xCR8' },
  { date: '2023.04', title: 'KSME IT Convergence Excellence Award', category: 'Award', body: 'M.S. student Sungho Chung received the excellence award from the Korean Society of Mechanical Engineers.', image: '/images/news/2023-04-ksme-award.jpg' },
  { date: '2023.02', title: 'KROC 2023', category: 'Conference', body: 'Conference participation and awards.', image: '/images/news/2023-02-kroc.jpg', images: ['/images/news/2023-02-kroc-2.jpg', '/images/news/2023-02-kroc-3.jpg', '/images/news/2023-02-kroc-4.jpg', '/images/news/2023-02-kroc-5.jpg', '/images/news/2023-02-kroc-6.jpg', '/images/news/2023-02-kroc-7.jpg'] },
  { date: '2022.12', title: 'Sogang ME Academic Festival', category: 'Lab Life', body: 'The lab joined the department academic festival.', image: '/images/news/2022-12-festival.jpg', images: ['/images/news/2022-12-festival-2.jpg'] },
  { date: '2022.08', title: 'Invited talks — Dr. Younggeol Cho & Dr. Hyung-Tae Seo', category: 'Announcement', body: 'Invited seminar talks at the lab.', image: '/images/news/2022-08-invited-talks.jpg', images: ['/images/news/2022-08-invited-talks-2.jpg', '/images/news/2022-08-invited-talks-3.jpg', '/images/news/2022-08-invited-talks-4.jpg'] },
  { date: '2022.05', title: 'First robot arm arrives at RIM Lab', category: 'Lab Life', body: 'The lab set up its first collaborative robot arm on the optical table.', image: '/images/news/2022-05-first-robot-arm.jpg' },
  { date: '2022.02', title: 'Best Paper Award, KSPE 2021', category: 'Award', body: 'Our work received the Best Paper Award at the Korean Society for Precision Engineering (KSPE) 2021 conference.', image: '/images/news/2022-02-kspe-award.jpg', images: ['/images/news/2022-02-kspe-award-2.jpg', '/images/news/2022-02-kspe-award-3.jpg', '/images/news/2022-02-kspe-award-4.jpg'] },
  { date: '2022.01', title: "RIM Lab's first paper published", category: 'Publication', body: '"Mechanical Variable Magnetic Gear Transmission: Concept and Preliminary Research" — the first paper produced by the lab — was published in IEEE Robotics and Automation Letters.', link: 'https://ieeexplore.ieee.org/document/9695205', image: '/images/news/2022-01-first-paper.jpg' },
  { date: '2022.04', title: 'Industry-academia project with Daeha Wire & Cable', category: 'Grant', body: 'Development of a robotic gripper and manipulator system for automated harness-cable assembly (2022.04 – 2025.05).' },
  { date: '2022.04', title: 'TIPA Green Venture project with Ecube Labs', category: 'Grant', body: 'Advanced waste-collection vehicle systems for collection automation and operator assistance.' },
  { date: '2022.05', title: 'ICRA 2022, Philadelphia, USA', category: 'Conference', body: 'The lab participated in IEEE ICRA 2022.', image: '/images/news/2022-05-icra.jpg', images: ['/images/news/2022-05-icra-2.jpg', '/images/news/2022-05-icra-3.jpg', '/images/news/2022-05-icra-4.jpg'] },
  { date: '2021.12', title: 'Graduate School Research Award — Edgar Lee', category: 'Award', body: 'Edgar Lee (Ph.D. student) was awarded 2nd place in the Graduate School Research Award at the Sogang ME academic festival.', image: '/images/news/2021-12-grad-research-award.jpg' },
  { date: '2021.09', title: 'Undergraduate interns win at the 20th Intelligent Creative Robot Contest', category: 'Award', body: 'Minho Kim, Yunseok Seol, Hyunseok Lee, Jaewoo Kim, Kangil Yoon, Jisu Lim, and Siyoung Hong received awards at the 20th Intelligent Creative Robot Contest. Congratulations!', image: '/images/news/2021-09-robot-contest.jpg', images: ['/images/news/2021-09-robot-contest-2.jpg', '/images/news/2021-09-robot-contest-3.jpg'] },
];

export const categoryColors: Record<NewsCategory, string> = {
  Announcement: 'text-cyan-300 border-cyan-300/40 bg-cyan-300/10',
  Conference: 'text-sky-300 border-sky-300/40 bg-sky-300/10',
  Award: 'text-amber-300 border-amber-300/40 bg-amber-300/10',
  Grant: 'text-emerald-300 border-emerald-300/40 bg-emerald-300/10',
  Publication: 'text-violet-300 border-violet-300/40 bg-violet-300/10',
  Members: 'text-rose-300 border-rose-300/40 bg-rose-300/10',
  'Lab Life': 'text-slate-300 border-slate-300/40 bg-slate-300/10',
};
