export type Pub = {
  title: string;
  authors: string;
  venue: string;
  year: number;
  type: 'journal' | 'conference' | 'domestic' | 'patent';
  link?: string;
  note?: string;
  /** Demo video: a YouTube video ID, a full URL, or a site path (e.g. /videos/pubs/xxx.mp4) */
  video?: string;
  /** Poster image for non-YouTube videos (path under /public) */
  videoThumb?: string;
  /** Representative/abstract figure (path under /public, e.g. /images/pubs/xxx.jpg) */
  image?: string;
};

export const publications: Pub[] = [
  { title: 'Automated Terminal-to-Housing Assembly System for Flat Ribbon Cable Harness', authors: 'E. Choi, J. Seo, S. Lee, S. Jeong*', venue: 'IEEE Transactions on Automation Science and Engineering (conditionally accepted)', year: 2026, type: 'journal', note: 'Preprint on arXiv', link: 'https://arxiv.org/abs/2608.06996', video: '3eF24n0M4sI', image: '/images/pubs/automated-terminal-to-housing-assembly-system-for-flat-ribbo.jpg' },
  { title: 'Ultra-Low-Impedance Robotic Gripper for High-Bandwidth and Transparent Physical Interaction', authors: 'J. Lee, A. Choi, S. Jeong*', venue: 'arXiv (ICRA 2027 late-breaking result)', year: 2026, type: 'journal', link: 'https://arxiv.org/abs/2608.09198', video: 'pyLLG74D9jI', image: '/images/pubs/ultra-low-impedance-robotic-gripper-for-high-bandwidth-and-t.jpg' },
  { title: 'Why Look at It at All?: Vision-Free Multifingered Blind Grasping Using Uniaxial Fingertip Force Sensing', authors: 'E. Lee, J. Choi, T. Kim, C. Nam*, S. Jeong*', venue: 'arXiv (under review)', year: 2026, type: 'journal', link: 'https://arxiv.org/abs/2602.07326', video: 'lJGHvHAex6g', image: '/images/pubs/why-look-at-it-at-all-vision-free-multifingered-blind-graspi.jpg' },
  { title: 'RIM Hand: A Robotic Hand with an Accurate Carpometacarpal Joint and Nitinol-Reinforced Skeletal Structure', authors: 'J. Lee, J. Han (co-first), D. Kim, S. Jeong*', venue: 'Soft Robotics', year: 2026, type: 'journal', link: 'https://journals.sagepub.com/doi/10.1177/21695172261423503', video: '9866GYPbY-E', image: '/images/pubs/rim-hand-a-robotic-hand-with-an-accurate-carpometacarpal-joi.jpg' },
  { title: 'Twisted String Actuation Module for Compact Robotic Finger with Extended Stroke, Reduced Hysteresis, and Bidirectional Operation', authors: 'C. Lee, B. Suthar*, S. Jeong*', venue: 'IEEE Robotics and Automation Letters', year: 2026, type: 'journal', link: 'https://ieeexplore.ieee.org/document/11299541', video: '_QcDDKlwtPs', image: '/images/pubs/twisted-string-actuation-module-for-compact-robotic-finger-w.jpg' },
  { title: 'Variable Transmission Mechanisms for Robotic Applications: A Review', authors: 'J. Park*, J. Lee, H.-T. Seo*, S. Jeong*', venue: 'IEEE Robotics and Automation Magazine', year: 2025, type: 'journal', link: 'https://ieeexplore.ieee.org/document/10682811', image: '/images/pubs/variable-transmission-mechanisms-for-robotic-applications-a-.jpg' },
  { title: 'Continuously Variable Transmission and Stiffness Actuator based on Actively Variable Four-Bar Linkage for Highly Dynamic Robot Systems', authors: 'J. Hur, H. Song, S. Jeong*', venue: 'IEEE Robotics and Automation Letters', year: 2024, type: 'journal', link: 'https://ieeexplore.ieee.org/document/10569041', video: 'Qudi73Vm4_c', image: '/images/pubs/continuously-variable-transmission-and-stiffness-actuator-ba.jpg' },
  { title: 'A Robotic Finger with a 4-bar Linkage-based Compact and Continuously Variable Active Transmission', authors: 'S. Chung, E. Sohn, S. Jeong*', venue: 'IEEE Robotics and Automation Letters', year: 2024, type: 'journal', link: 'https://ieeexplore.ieee.org/document/10531636', video: 'rm8DG30cxmQ', image: '/images/pubs/a-robotic-finger-with-a-4-bar-linkage-based-compact-and-cont.jpg' },
  { title: 'Coaxial Magnetic Gear-based Tool-Changing System', authors: 'H. Song, J. Hur, S. Jeong*', venue: 'IEEE Access', year: 2024, type: 'journal', link: 'https://ieeexplore.ieee.org/document/10458127', video: 'zuAvOsLDOUI', image: '/images/pubs/coaxial-magnetic-gear-based-tool-changing-system.jpg' },
  { title: 'A Modular Robotic Platform for Biological Research: Cell Culture Automation and Remote Experimentation', authors: 'J. Hamm, S. Lim, J. Park, J. Kang, I. Lee, Y. Lee, J. Kang, Y. Jo, J. Lee, S. Lee, M. C. Ratri, A. I. Brilian, S. Lee, S. Jeong, K. Shin*', venue: 'Advanced Intelligent Systems', year: 2024, type: 'journal', link: 'https://onlinelibrary.wiley.com/doi/10.1002/aisy.202300566', note: 'Journal cover', image: '/images/pubs/a-modular-robotic-platform-for-biological-research-cell-cult.jpg' },
  { title: 'Magnetic Gear-based Actuator: A Framework of Design, Optimization, and Disturbance Observer-based Torque Control', authors: 'H. Song, E. Lee, H.-T. Seo*, S. Jeong*', venue: 'IEEE Robotics and Automation Letters', year: 2023, type: 'journal', link: 'https://ieeexplore.ieee.org/document/10242358', video: '64h1yNFKHZI', image: '/images/pubs/magnetic-gear-based-actuator-a-framework-of-design-optimizat.jpg' },
  { title: 'Coaxial Magnetic Gear-Based Actuation Module for Robotic Applications: Torque Control Using Magnetic Spring', authors: 'H. Song, E. Lee, H.-T. Seo*, S. Jeong*', venue: 'IEEE ICRA (video presentation)', year: 2023, type: 'conference' },
  { title: 'Variable Transmission between Series Elastic Actuator and Quasi-Direct Drive Actuator in One Actuator for Dynamic Interaction Tasks', authors: 'J. Hur, H. Song, T. Lee, W. Lee, J. Kim, S. Jeong*', venue: 'IEEE IROS (late-breaking result)', year: 2023, type: 'conference', video: 'Qudi73Vm4_c' },
  { title: 'FLEXotendon Glove-III: Voice-Controlled Soft Robotic Hand Exoskeleton With Novel Fabrication Method and Admittance Grasping Control', authors: 'P. Tran*, S. Jeong, F. Lyu, K. Herrin, S. Bhatia, D. Elliott, S. Kozin, J. P. Desai', venue: 'IEEE/ASME Transactions on Mechatronics', year: 2022, type: 'journal', link: 'https://ieeexplore.ieee.org/document/9718020', video: 'OM03dU-8-aQ', image: '/images/pubs/flexotendon-glove-iii-voice-controlled-soft-robotic-hand-exo.jpg' },
  { title: 'Mechanical Variable Magnetic Gear Transmission: Concept and Preliminary Research', authors: 'E. Lee, H. Song, J. Jeong, S. Jeong*', venue: 'IEEE Robotics and Automation Letters', year: 2022, type: 'journal', link: 'https://ieeexplore.ieee.org/document/9695205', video: 'NYoOHJvqkF4', image: '/images/pubs/mechanical-variable-magnetic-gear-transmission-concept-and-p.jpg' },
  { title: 'The MSC Prosthetic Hand: Rapid, Powerful, and Intuitive', authors: 'Y. Cho, Y. Lee, P. Kim, S. Jeong*, K.-S. Kim*', venue: 'IEEE Robotics and Automation Letters', year: 2022, type: 'journal', link: 'https://ieeexplore.ieee.org/document/9670648', video: 'Rkd7FrLRpiQ', image: '/images/pubs/the-msc-prosthetic-hand-rapid-powerful-and-intuitive.jpg' },
  { title: 'Magnetic Gear Based Actuator: Design and Optimization', authors: 'H. Song, E. Lee, S. Jeong', venue: 'ICCAS', year: 2022, type: 'conference', link: 'https://ieeexplore.ieee.org/document/10003859', image: '/images/pubs/magnetic-gear-based-actuator-design-and-optimization.jpg' },
  { title: 'A Review: Hand Exoskeleton Systems, Clinical Rehabilitation Practices, and Future Prospects', authors: 'P. Tran, S. Jeong (co-first), K. Herrin, J. P. Desai', venue: 'IEEE Transactions on Medical Robotics and Bionics', year: 2021, type: 'journal', link: 'https://ieeexplore.ieee.org/document/9499111', image: '/images/pubs/a-review-hand-exoskeleton-systems-clinical-rehabilitation-pr.jpg' },
  { title: 'Mechanical Design and Evaluation of a Selectively-Actuated MRI-Compatible Continuum Neurosurgical Robot', authors: 'S. S. Cheng, X. Wang, S. Jeong, M. Kole, S. Roys, R. Gullapalli', venue: 'IEEE ICRA', year: 2021, type: 'conference', link: 'https://ieeexplore.ieee.org/document/9636128', image: '/images/pubs/mechanical-design-and-evaluation-of-a-selectively-actuated-m.jpg' },
  { title: 'Applications: Twisted String Actuation-Based Compact Automatic Transmission', authors: 'S. Jeong, Y. Lee, K.-S. Kim*', venue: 'IEEE ICRA', year: 2021, type: 'conference', link: 'https://ieeexplore.ieee.org/document/9561453', video: 'RxmGPmoC-yg', image: '/images/pubs/applications-twisted-string-actuation-based-compact-automati.jpg' },
  { title: 'FLEXotendon Glove-III: Soft Robotic Hand Rehabilitation Exoskeleton for Spinal Cord Injury', authors: 'P. Tran, S. Jeong (co-first), K. Herrin, S. Bhatia, S. Kozin, J. P. Desai', venue: 'IEEE ICRA', year: 2021, type: 'conference', link: 'https://ieeexplore.ieee.org/document/9560993', video: 'OM03dU-8-aQ', image: '/images/pubs/flexotendon-glove-iii-soft-robotic-hand-rehabilitation-exosk.jpg' },
  { title: 'Design and Control of 5-DoF Robotically Steerable Catheter for the Delivery of the Mitral Valve Implant', authors: 'N. Nayar, S. Jeong, J. P. Desai', venue: 'IEEE ICRA', year: 2021, type: 'conference', link: 'https://ieeexplore.ieee.org/document/9561146', image: '/images/pubs/design-and-control-of-5-dof-robotically-steerable-catheter-f.jpg' },
  { title: 'Modeling and Control of a 2-DoF Meso-scale Continuum Robotic Tool for Pediatric Neurosurgery', authors: 'Y. Chitalia, S. Jeong (co-first), K. Yamamoto, J. Chern, J. P. Desai', venue: 'IEEE Transactions on Robotics', year: 2021, type: 'journal', link: 'https://ieeexplore.ieee.org/document/9248011', image: '/images/pubs/modeling-and-control-of-a-2-dof-meso-scale-continuum-robotic.jpg' },
  { title: 'Design, Modeling, and Control of a Coaxially Aligned Steerable (COAST) Guidewire Robot', authors: 'S. Jeong, Y. Chitalia, J. P. Desai', venue: 'IEEE Robotics and Automation Letters', year: 2020, type: 'journal', link: 'https://ieeexplore.ieee.org/document/9126186', video: 'RRY6Vp9R0aA', image: '/images/pubs/design-modeling-and-control-of-a-coaxially-aligned-steerable.jpg' },
  { title: 'Miniature Force Sensor based on Dual-photointerrupter with High Linearity and Disturbance Compensation', authors: 'S. Jeong, Y. Chitalia, J. P. Desai', venue: 'IEEE Sensors Journal', year: 2020, type: 'journal', link: 'https://ieeexplore.ieee.org/document/9003240', image: '/images/pubs/miniature-force-sensor-based-on-dual-photointerrupter-with-h.jpg' },
  { title: 'Towards FBG-Based Shape Sensing for Micro-scale and Meso-Scale Continuum Robots with Large Deflection', authors: 'Y. Chitalia, N. Deaton, S. Jeong, N. Rahman, J. P. Desai', venue: 'IEEE Robotics and Automation Letters', year: 2020, type: 'journal', link: 'https://ieeexplore.ieee.org/document/8972454', image: '/images/pubs/towards-fbg-based-shape-sensing-for-micro-scale-and-meso-sca.jpg' },
  { title: 'Design and Kinematics Analysis of a Robotic Pediatric Neuroendoscope Tool Body', authors: 'Y. Chitalia, S. Jeong, N. Deaton, J. Chern, J. P. Desai', venue: 'IEEE/ASME Transactions on Mechatronics', year: 2020, type: 'journal', link: 'https://ieeexplore.ieee.org/document/8963646', image: '/images/pubs/design-and-kinematics-analysis-of-a-robotic-pediatric-neuroe.jpg' },
  { title: 'Integration of Self-Sealing Suction Cups on the FLEXotendon Glove-II Robotic Exoskeleton System', authors: 'S. Jeong, P. Tran, J. P. Desai', venue: 'IEEE Robotics and Automation Letters', year: 2020, type: 'journal', link: 'https://ieeexplore.ieee.org/document/8957292', video: 'HTXwTqTGt8E', image: '/images/pubs/integration-of-self-sealing-suction-cups-on-the-flexotendon-.jpg' },
  { title: 'Patient-specific, Voice-controlled, Robotic FLEXotendon Glove-II System for Spinal Cord Injury', authors: 'P. Tran, S. Jeong (co-first), S. L. Wolf, J. P. Desai', venue: 'IEEE Robotics and Automation Letters', year: 2020, type: 'journal', link: 'https://ieeexplore.ieee.org/document/8957079', image: '/images/pubs/patient-specific-voice-controlled-robotic-flexotendon-glove-.jpg' },
  { title: 'Towards the Development of a Robotic Transcatheter Delivery System for Mitral Valve Implant', authors: 'N. Nayar, S. Jeong, J. P. Desai', venue: 'IEEE IROS', year: 2020, type: 'conference', link: 'https://ieeexplore.ieee.org/abstract/document/9341551', image: '/images/pubs/towards-the-development-of-a-robotic-transcatheter-delivery-.jpg' },
  { title: 'Towards the Development of an Ultrasound-Guided Robotically Steerable Guidewire', authors: 'A. Sarma, G. Collins, N. Nayar, Y. Chitalia, S. Jeong, B. Lindsey, J. P. Desai', venue: 'ISMR', year: 2020, type: 'conference', link: 'https://ieeexplore.ieee.org/document/9312925', image: '/images/pubs/towards-the-development-of-an-ultrasound-guided-robotically-.jpg' },
  { title: 'Towards the Design and Development of a Pediatric Neuroendoscope Tool', authors: 'Y. Chitalia, S. Jeong, J. Bok, V. Nguyen, S. Melkote, J. J. Chern, J. P. Desai', venue: 'IEEE IROS', year: 2019, type: 'conference', link: 'https://ieeexplore.ieee.org/document/8968186', image: '/images/pubs/towards-the-design-and-development-of-a-pediatric-neuroendos.jpg' },
  { title: 'Voice-Controlled Flexible Exotendon (FLEXotendon) Glove for Hand Rehabilitation', authors: 'P. Tran, S. Jeong, J. P. Desai', venue: 'IEEE IROS', year: 2019, type: 'conference', link: 'https://ieeexplore.ieee.org/document/8967669', image: '/images/pubs/voice-controlled-flexible-exotendon-flexotendon-glove-for-ha.jpg' },
  { title: 'Design of Robot Hand with Pneumatic Dual-Mode Actuation Mechanism Powered by Chemical Gas Generation Method', authors: 'K. R. Kim, S. H. Jeong, P. Kim, K.-S. Kim', venue: 'IEEE Robotics and Automation Letters', year: 2018, type: 'journal', link: 'https://ieeexplore.ieee.org/document/8408498', image: '/images/pubs/design-of-robot-hand-with-pneumatic-dual-mode-actuation-mech.jpg' },
  { title: 'A 2-Speed Small Transmission Mechanism Based on Twisted String Actuation and a Dog Clutch', authors: 'S. H. Jeong, K.-S. Kim', venue: 'IEEE Robotics and Automation Letters', year: 2018, type: 'journal', link: 'https://ieeexplore.ieee.org/document/8253814', video: 'Y1uceDzhjKY', image: '/images/pubs/a-2-speed-small-transmission-mechanism-based-on-twisted-stri.jpg' },
  { title: 'Design of a Miniature Force Sensor based on Photointerrupter for Robotic Hand', authors: 'S. H. Jeong, H. J. Lee, K. R. Kim, K.-S. Kim', venue: 'Sensors and Actuators A: Physical', year: 2018, type: 'journal', link: 'https://www.sciencedirect.com/science/article/pii/S0924424717309317', image: '/images/pubs/design-of-a-miniature-force-sensor-based-on-photointerrupter.jpg' },
  { title: 'Design and Analysis of the Active Dual-Mode Twisting Actuation Mechanism', authors: 'S. H. Jeong, Y. J. Shin, K.-S. Kim', venue: 'IEEE/ASME Transactions on Mechatronics', year: 2017, type: 'journal', link: 'https://ieeexplore.ieee.org/document/8089392', video: 'QBQMZsSQJQM', image: '/images/pubs/design-and-analysis-of-the-active-dual-mode-twisting-actuati.jpg' },
  { title: 'Designing Anthropomorphic Robot Hand With Active Dual-Mode Twisted String Actuation Mechanism and Tiny Tension Sensors', authors: 'S. H. Jeong, K.-S. Kim, S. Kim', venue: 'IEEE Robotics and Automation Letters', year: 2017, type: 'journal', link: 'https://ieeexplore.ieee.org/document/7805142', video: '5PtXTI1t3Po', image: '/images/pubs/designing-anthropomorphic-robot-hand-with-active-dual-mode-t.jpg' },
  { title: 'Control of and Experimentation on an Active Dual-Mode Twisted String Actuation Mechanism', authors: 'S. H. Jeong, K.-S. Kim, S. Kim', venue: 'IEEE AIM', year: 2017, type: 'conference', link: 'https://ieeexplore.ieee.org/document/8014147' },
  { title: 'Design of Small Mobile Robot Remotely Controlled by an Android Operating System via Bluetooth and NFC Communication', authors: 'K. R. Kim, S. H. Jeong, W. Y. Kim, Y. Jeon, K.-S. Kim, J. H. Hong', venue: 'URAI', year: 2017, type: 'conference', link: 'https://ieeexplore.ieee.org/document/7992864', image: '/images/pubs/design-of-small-mobile-robot-remotely-controlled-by-an-andro.jpg' },
  { title: 'Development of a Robotic Finger with an Active Dual-Mode Twisting Actuation and a Miniature Tendon Tension Sensor', authors: 'S. H. Jeong, K.-S. Kim, S. Kim', venue: 'IEEE AIM', year: 2016, type: 'conference', link: 'https://ieeexplore.ieee.org/document/7576734', note: 'Best Student Paper Award · Best Mechatronics Student Paper Award (ASME/DSCD)', video: 'Ctz6tUdFF8s', image: '/images/pubs/development-of-a-robotic-finger-with-an-active-dual-mode-twi.jpg' },
  { title: 'Dual-Mode Twisting Actuation Mechanism with an Active Clutch for Active Mode-Change and Simple Relaxation Process', authors: 'S. H. Jeong, Y. J. Shin, K.-S. Kim, S. Kim', venue: 'IEEE IROS', year: 2015, type: 'conference', link: 'https://ieeexplore.ieee.org/abstract/document/7354205', image: '/images/pubs/dual-mode-twisting-actuation-mechanism-with-an-active-clutch.jpg' },
  { title: '다발 하네스 케이블 조립 자동화 시스템 구현을 위한 메커니즘 설계', authors: '최은규, 서준호, 정석환', venue: '국방로봇학회 논문집', year: 2024, type: 'domestic', link: 'https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE12035418', image: '/images/pubs/harness-cable-assembly-mechanism-design-2024.jpg' },
  { title: '방향을 가진 물체 인식 알고리즘과 조립 전략을 활용한 단일 하네스 케이블 조립 공정', authors: '이승민, 정앤드류, 정석환', venue: '국방로봇학회 논문집', year: 2023, type: 'domestic', link: 'https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE11343462', image: '/images/pubs/single-harness-cable-assembly-process-2023.jpg' },
];
